# Generated by Django 5.2.4 on 2025-07-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
