# Generated by Django 5.2.4 on 2025-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisor', '0002_queueentry_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='output_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
