# Generated by Django 5.2.4 on 2025-07-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisor', '0003_queueentry_output_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='output_file_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(default='na_fila', max_length=50),
        ),
    ]
