# Generated by Django 5.2.4 on 2025-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisor', '0004_queueentry_file_path_queueentry_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='file_path',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='mode',
            field=models.CharField(default='completa', max_length=50),
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
